### PR TITLE
upgrade to c++17

### PR DESCRIPTION
**Pull request by condorscientific**
upgrading the flags dependency cmake files to c++17

### CODE REVIEW

**Comment by thraneh** [comment]
Sorry, can't do that.

On OSX-64, the current C++ compiler that comes with Miniforge is clang 11.1, which has C++14 as the default target.
Also, Abseil does not play well when mixing C++14 and C++17 due to std::string_view ABI compatibility and their own workarounds.

What issue are you seeing?

**Comment by condorscientific** [comment]
When running `make VERBOSE=1` for the roq-samples:

cd /home/ubuntu/dc/roq/roq-samples/src/roq/samples/example-1/flags &&
/usr/bin/c++  -I/home/ubuntu/dc/roq/roq-samples/src -isystem
/home/ubuntu/conda/include  -MD -MT src/roq/sample$
/example-1/flags/CMakeFiles/roq-samples-example-1-flags.dir/flags.cpp.o -MF
CMakeFiles/roq-samples-example-1-flags.dir/flags.cpp.o.d -o
CMakeFiles/roq-samples-example-1-flags.dir/fl$
gs.cpp.o -c
/home/ubuntu/dc/roq/roq-samples/src/roq/samples/example-1/flags/flags.cpp
In file included from
/home/ubuntu/dc/roq/roq-samples/src/roq/samples/example-1/flags/flags.cpp:3:
/home/ubuntu/dc/roq/roq-samples/src/roq/samples/example-1/flags/flags.h:13:15:
error: ‘string_view’ in namespace ‘std’ does not name a type
   13 |   static std::string_view deribit_exchange();
      |               ^~~~~~~~~~~
/home/ubuntu/dc/roq/roq-samples/src/roq/samples/example-1/flags/flags.h:13:10:
note: ‘std::string_view’ is only available from C++17 onwards
   13 |   static std::string_view deribit_exchange();
      |          ^~~


Changing it to c++17 allows it to compile. I remember reading in your docs
that you use a version of string_view that is backwards compatible, perhaps
we need to update the includes for the flags/ to point towards this
string_view?

**Comment by thraneh** [comment]
You shouldn't compile with the default compiler from the system.

From inside your conda environment, try do this:

```
conda install -y gxx_linux-64 git make cmake abseil-cpp
```

Also run `cmake .` from inside the conda environment, it should automatically find the compiler from somewhere under `$CONDA_PREFIX`.

From Linux, I find this in my `CMakeCache.txt`

```
CMAKE_CXX_COMPILER:FILEPATH=/home/thraneh/dev/roq-dev/opt/conda/bin/x86_64-conda-linux-gnu-c++
```

**Comment by thraneh** [comment]
I believe this was resolved by using the Conda/Miniforge provided compiler.

**Pull request closed without merging**
